---
repo-name: peripherals-freshworks
categories:
- ITSM
display-name: Fresh Works
manufacturer: Freshworks
product: Freshservice
description: Freshworks makes it fast and easy for businesses to delight their customers and employees. ... Unlike legacy software, Freshworks builds tech that works for everyone, making it easy for IT, customer service, sales, marketers and HR to do their job and delight their customers..